# url with placeholder elements to exchange with search text
TEMP_SEARCH_STR: 'person thumbs down'

# where images will be downloaded to
CHROME_DOWNLOAD_DIR: ./downloads/thumbs_down_samples
FILE_NAME:
FILE_EXT:

# how many images, for random selection only
NUMBER_OF_IMAGES: 4
RANDOM: True

# if not random, provide range of pics
START_RANGE_OF_IMAGES: 0
END_RANGE_OF_IMAGES: 0

# can configure logging for debug mode
LOGGING_DEBUG_MODE: False

##
# End user input // begin static config
##

# Chrome base/info
BASE_URL: https://www.google.com/search?tbm=isch&q={QUERY_PLACEHOLDER}
QUERY_REPL: '{QUERY_PLACEHOLDER}'

# Selenium attribs
THUMBNAIL_CLASS_ELEMENT: 'v4dQwb'
IMG_CLASS_ELEMENT: 'n3VNCb'
IMAGES_BASE: 'rg_i'

# Chrome Specific attribs
chrome_settings_args:
  - --headless
  - --no-sandbox
  - --disable-dev-shm-usage